#!/bin/bash -e

. functions

# See groups: dnf group list hidden -v

# Main system
install @standard
install @hardware-support
install @multimedia
install @fonts
install @networkmanager-submodules
install @base-x
remove abrt*
sudo dracut --force  # Enable Plymouth

# Office
install @libreoffice

# Basic desktop
install lightdm-gtk
install breeze-cursor-theme
install elementary-xfce-icon-theme
install greybird-gtk2-theme
install greybird-gtk3-theme
install lxappearance
install xfce4-terminal
install i3lock
install feh

# Fonts
install hack-fonts
install google-droid-serif-fonts
install google-droid-sans-fonts 
install google-droid-sans-mono-fonts
install adobe-source-code-pro-fonts
install linux-libertine-fonts 
install linux-libertine-biolinum-fonts 
install google-croscore-arimo-fonts 
install google-croscore-cousine-fonts
install google-croscore-tinos-fonts
install google-crosextra-caladea-fonts
install google-crosextra-carlito-fonts

# Better font rendering with sub-pixel smoothing
install freetype-freeworld

# System tools
install setroubleshoot
install setools
install python3-dnf-plugins-extras-leaves
install qt-config
install qt5ct
install qt5-qtstyleplugins
install pavucontrol
install wmctrl
install xdotool
install NetworkManager-openvpn 
install NetworkManager-openvpn-gnome
install xfce4-power-manager
install acpid

# CLI applications
install htop
install mc 
install NetworkManager-tui
install ncdu
install inxi
install numlockx
install ffmpeg 
install youtube-dl 
install streamlink
install vim-enhanced vim-X11

# GUI applications
install geany
install geany-plugins-geanyextrasel
install geany-plugins-spellcheck
install gparted
install xarchiver
install xfburn
install viewnior 
install firefox
install google-chrome-stable
install doublecmd-gtk 
install speedcrunch 
install smplayer
install evince
install audacity-freeworld 
install vlc
install thunderbird 
install VirtualBox
install sqliteman
install meld
install keepassxc
install dropbox
install hexchat
install docker

# Tweaks
sudo systemctl enable lightdm
sudo systemctl set-default graphical.target
    sudo sed -i 's|#greeter-setup-script=|greeter-setup-script=/usr/bin/numlockx on|g' /etc/lightdm/lightdm.conf
