#!/bin/bash -e

. dotfiles


if (( EUID != 0 )); then
    echo "Please run as root"
    exit
fi

nr_of_elements=${#SUDO_FILES[@]}
for (( i = 0; i < nr_of_elements; i += 2 )); do
    file=${SUDO_FILES[i]}
    target=${SUDO_FILES[i + 1]}
    handle_file "$file" "$target" "sudo-flag"
done

protect "$HOME/Utility/scripts/stats/brightness"
