#!/bin/bash -e

. functions

# From source
mkdir --parents ~/Utility/bin
mkdir --parents ~/Utility/repos
cd ~/Utility/repos

echo "==> i3-gaps (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" != [nN] ]]; then
    install dh-autoreconf
    install libxcb-devel xcb-util-keysyms-devel xcb-util-devel xcb-util-wm-devel
    install xcb-util-xrm-devel yajl-devel libXrandr-devel startup-notification-devel 
    install libev-devel xcb-util-cursor-devel libXinerama-devel libxkbcommon-devel
    install libxkbcommon-x11-devel pcre-devel pango-devel git gcc
fi
if [[ "$response" == [gG] ]]; then
    git clone https://www.github.com/Airblader/i3 i3-gaps
    cd i3-gaps
    autoreconf --force --install
    rm -rf build/
    mkdir -p build && cd build/
    ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers
    make
    sudo make install
    cd ../..
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/i3-gaps.tgz
    cd i3-gaps/build
    sudo make install
    cd ../..
fi

echo "==> i3blocks-gaps (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/Airblader/i3blocks-gaps.git
    cd i3blocks-gaps
    make all
    sudo make install
    cd ..
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/i3blocks-gaps.tgz
    cd i3blocks-gaps
    sudo make install
    cd ..
fi

echo "==> rofi (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" != [nN] ]]; then
    install bison flex librsvg2-devel check-devel
fi
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/DaveDavenport/rofi.git
    cd rofi
    git submodule update --init
    autoreconf -i
    mkdir build
    cd build
    ../configure
    make
    cd ../..
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/rofi.tgz
fi
if [[ "$response" != [nN] ]]; then
    ln -sf ~/Utility/repos/rofi/build/rofi ~/Utility/bin/rofi
fi

echo "==> compton (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" != [nN] ]]; then
    install gcc libconfig-devel pcre-devel libdrm mesa-libGL-devel asciidoc 
    install xorg-x11-utils hicolor-icon-theme libXcomposite-devel dbus-devel
    install desktop-file-utils 
fi
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/chjj/compton.git
    ( cd compton; make )
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/compton.tgz
fi
if [[ "$response" != [nN] ]]; then
    ln -sf ~/Utility/repos/compton/compton ~/Utility/bin/compton
fi

echo "==> gtk3-nocsd (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" != [nN] ]]; then
    install pkgconfig gtk3-devel gtk+-devel gobject-introspection-devel
fi
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/PCMan/gtk3-nocsd.git
    ( cd gtk3-nocsd; make )
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/gtk3-nocsd.tgz
fi
if [[ "$response" != [nN] ]]; then
    ln -sf ~/Utility/repos/gtk3-nocsd/gtk3-nocsd ~/Utility/bin/gtk3-nocsd
fi

echo "==> ksuperkey (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" != [nN] ]]; then
    install libXtst-devel
fi
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/hanschen/ksuperkey.git
    ( cd ksuperkey; make )
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/ksuperkey.tgz
fi
if [[ "$response" != [nN] ]]; then
    ln -sf ~/Utility/repos/ksuperkey/ksuperkey ~/Utility/bin/ksuperkey
fi

echo "==> presentation-switch (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/skontar/presentation-switch.git
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/presentation-switch.tgz
fi
if [[ "$response" != [nN] ]]; then
    ln -sf ~/Utility/repos/presentation-switch/presentation_switch.py ~/Utility/bin/presentation-switch
fi

echo "==> update-checker (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/skontar/update-checker.git
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/update-checker.tgz
fi
if [[ "$response" != [nN] ]]; then
    ln -sf ~/Utility/repos/update-checker/update_checker.py ~/Utility/bin/update-checker
fi

echo "==> bash-git-prompt (from Git / Zip / Not at all):"
read -rsn1 response
if [[ "$response" == [gG] ]]; then
    git clone https://github.com/magicmonty/bash-git-prompt.git
elif [[ "$response" == [zZ] ]]; then
    tar -zxf ../zips/bash-git-prompt.tgz
fi
