#!/bin/bash -e

. dotfiles


nr_of_elements=${#FILES[@]}
for (( i = 0; i < nr_of_elements; i += 2 )); do
    file=${FILES[i]}
    target=${FILES[i + 1]}
    handle_file "$file" "$target"
done


chmod 640 ../confidential/ssh/config
