#!/bin/bash

sudo yum install epel-release

sudo yum group install -y "Base" 
sudo yum group install -y "Common NetworkManager submodules" 
sudo yum group install -y "Fonts" 
sudo yum group install -y "Graphics Creation Tools" 
sudo yum group install -y "Internet Browser" 
sudo yum group install -y "Multimedia" 
sudo yum group install -y "Office Suite and Productivity" 
sudo yum group install -y "Printing Client" 
sudo yum group install -y "X Window System" 
sudo yum group install -y "Xfce"

sudo yum install -y lightdm
sudo yum remove -y gdm
sudo systemctl enable lightdm
sudo systemctl set-default graphical.target

sudo yum install -y google-droid*
sudo yum install -y oxygen-cursor-themes
sudo yum install -y xfce4-*
sudo yum install -y gvfs
sudo yum install -y network-manager-applet
sudo yum install -y xdg-user-dirs
sudo yum install -y evince
sudo yum install -y ristretto
sudo yum install -y mousepad
sudo yum install -y xarchiver
sudo yum install -y brasero
sudo yum install -y htop
sudo yum install -y powertop
sudo yum install -y tlp


sudo yum install -y http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm
sudo yum install -y flash-plugin

sudo yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
sudo yum install -y https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm

sudo yum install -y smplayer
sudo yum install -y vlc


# Set appearance - themes, fonts, slight hinting
# Add keyboard layouts
# Configure sudo to use root password
# Create yum update --security script
# Setup locking in /usr/bin/xflock4
# Firefox - install uBlock
# Enable tlp

# Panel
# W | LLL | Windows | Weather Pulse Notification Keyboard Clock |

# Check:
# * Screen tearing
# * Youtube
# * Media playback + sound
# * USB Automount
# * Powertop

# Remove abrt
# Update

# Disable auditd - fails to start sometimes
# Disable postfix
# Disable ssh
# Disable udisks2

# Change root password
