#!/bin/bash

# /etc/acpi/events/dockconf
#
# event=ibm/hotkey
# action=/etc/acpi/actions/dock.sh "%e"

# /etc/acpi/actions/dock.sh
#
# #!/bin/bash
#
# su -lc "DISPLAY=:0.0 action-dock \"$1\"" skontar

# ibm/hotkey LEN0068:00 00000080 00006030

# Debugging
echo ">>> $( date +"%-k:%M:%S" ) Dock! *$1*"

state=$( cut -d " " -f 4 <<< "$1" )

if [[ "$state" == "00006030" ]]; then
    # Dock changed
    echo "> Dock changed"
    displays auto
    pkill -RTMIN+1 i3blocks
fi
