#!/bin/bash

# Do every xrandr command separated to workaround Fedora bug about not waking some monitors.
# Change DPI to consistent value so some applications which use it have consistent font sizes.

D_LAPTOP="eDP1"
D_SINGLE="HDMI2"
D_BACKUP="DP2" # Backup projector port, t470s has none...
D_DUAL_1="DP2-1"
D_DUAL_2="DP2-2"


all_off() {
    xrandr --output "$D_LAPTOP" --off
    xrandr --output "$D_DUAL_1" --off
    xrandr --output "$D_DUAL_2" --off
    xrandr --output "$D_SINGLE" --off
    xrandr --output "$D_BACKUP" --off
}

single_screen() {
    xrandr --output "$D_SINGLE" --primary --auto

    xrandr --dpi 96x96
    echo "Single screen"
    notify-send "Single screen" -t 3000
}

dual_screen() {
    xrandr --output "$D_DUAL_2" --primary --auto
    #~ xrandr --output "$D_DUAL_2" --auto --right-of "$D_DUAL_1"

    xrandr --dpi 96x96
    echo "Dual screen"
    notify-send "Dual Screen" -t 3000
}

laptop_only() {
    xrandr --output "$D_LAPTOP" --primary --auto

    xrandr --dpi 96x96
    echo "Laptop only"
    notify-send "Laptop only" -t 3000
}

mirror() {
    xrandr --output "$1" --primary --mode "$2"
    xrandr --output "$D_LAPTOP" --same-as "$1" --mode 1920x1080 --scale-from "$2"

    if [[ "$1" != "$D_SINGLE" ]]; then
        xrandr --output "$D_SINGLE" --off
    fi
    if [[ "$1" != "$D_BACKUP" ]]; then
        xrandr --output "$D_BACKUP" --off
    fi

    xrandr --dpi 96x96
    echo "Mirror"
    notify-send "Mirror" -t 3000
}

check_available() {
    # Primary projector port - preferred
    if grep -q -s "$D_SINGLE connected" <<< "$1"; then
        echo "$D_SINGLE"
    fi
    # Backup projector (VGA?)
    if grep -q -s "$D_BACKUP connected" <<< "$1"; then
        echo "$D_BACKUP"
    fi
}

kill_apps() {
    compositor-stop
}

restart_apps() {
    sleep 2
    i3-msg restart
}

get_resolutions() {
    lines=$( sed -n "/$2 connected/,/connected/p" <<< "$1\nconnected" )
    sed -n -r -e 's/^  [[:space:]]*([[:digit:]]+x[[:digit:]]+).*$/\1/p' <<< "$lines"
}


notify-send "Changing screens..." -t 2000

kill_apps

case "$1" in
    "auto")
        xrandr_output=$( xrandr )
        all_off
        if grep -q -E "$D_DUAL_2 connected" <<< "$xrandr_output"; then
            dual_screen
        elif grep -q -E "$D_SINGLE connected" <<< "$xrandr_output"; then
            single_screen
        else
            laptop_only
        fi
        ;;
    "single")
        all_off
        single_screen
        ;;
    "dual")
        all_off
        dual_screen
        ;;
    "mirror")
        xrandr_output=$( xrandr )
        output_screen=$( check_available "$xrandr_output" )
        if [[ -n "$output_screen" ]]; then
            resolutions=( $( get_resolutions "$xrandr_output" "$output_screen" ) )
            if command -v yad > /dev/null; then
                selected_resolution=$( yad --list --width=250 --height=200 \
                                       --title "Select resolution" --no-headers --separator="" \
                                       --column="" "${resolutions[@]}" )
                if (( $? != 0 )); then
                    exit 2
                fi
            else
                notify-send 'You need `yad` installed to select resolution' -t 3000
                selected_resolution="${resolutions[0]}"
            fi
            all_off
            mirror "$output_screen" "$selected_resolution"
        else
            notify-send "No projector connected" -t 3000
        fi
        ;;
    *)
        all_off
        laptop_only
        ;;
esac

restart_apps
