#!/bin/bash

# Layout change must be inlined as xflock4 deletes path
setxkbmap -model pc104 -layout us -option grp:caps_toggle
pkill -RTMIN+3 i3blocks

compositor-stop  # Needed so notifications are not over lock screen
i3lock -n -i ~/Utility/confidential/wallpapers/converted/blue_planets_right.png -c 000000 -f
compositor-start

# Only version 2.8 of i3lock fixes this, but they reverted it
# i3lock -i ~/Utility/confidential/wallpapers/converted/blue_planets_both.png -c 000000 -f
