#!/bin/bash

pgrep thunderbird || thunderbird &
pgrep doublecmd || doublecmd &
pgrep firefox || firefox &
pgrep hexchat || hexchat &
pgrep xfce4-terminal || i3-msg 'workspace "6:  "; exec xfce4-terminal; exec xfce4-terminal'
sleep 2
pgrep chromium || i3-msg 'workspace "7:  "; exec calendar'
sleep 2
pgrep pycharm || /home/skontar/Programs/pycharm-community-2020.1/bin/pycharm.sh &

sleep 20
for win in $(wmctrl -l | awk -F' ' '{print $1}'); do
    wmctrl -i -r $win -b remove,demands_attention
done
