#!/bin/bash

if [[ "$( dropbox status )" == "Dropbox isn't running!" ]]; then
    notify-send -t 500 "Starting Dropbox..."
    dropbox start
else
    notify-send -t 500 "Stopping Dropbox..."
    dropbox stop
fi
