#!/bin/bash

if pgrep keepassxc; then
    notify-send -t 500 "Closing KeePassXC..."
    wmctrl -c "KeePassXC"
else
    notify-send -t 500 "Starting KeePassXC..."
    i3-msg workspace "10:  "
    keepassxc &
fi

