#!/bin/bash

warm_color="#ffff00"
critical_color="#ff0000"

cpu=$( top -bn2 | awk '/Cpu\(s\)/ { value = $8 } END { print int(100 - value) }' )

temp_string=$( </sys/class/thermal/thermal_zone3/temp )
temp=$(( temp_string / 1000 ))

if (( temp > 85 )); then
    thermo="<span color=\"$critical_color\"> $temp°C</span>"
elif (( temp > 75 )); then
    thermo="<span color=\"$warm_color\"> $temp°C</span>"
elif (( temp > 70 )); then
    thermo=" $temp°C"
elif (( temp > 55 )); then
    thermo=" $temp°C"
elif (( temp > 40 )); then
    thermo=" $temp°C"
else
    thermo=" $temp°C"
fi

echo " $cpu% $thermo"
