#!/bin/bash

if [[ $BLOCK_BUTTON == "1" ]]; then
    if ! wmctrl -F -c "Calendar popup"; then
        yad --calendar --no-buttons --title "Calendar popup" &> /dev/null &
    fi
fi

date -d "+20 seconds" +"  %a %-e %b  <b>%-k:%M</b>"
date -d "+20 seconds" +" <b>%-k:%M</b>"
