#!/bin/bash

if [[ $BLOCK_BUTTON == "1" ]]; then
    if ! wmctrl -F -c "Disk popup"; then
        notify-send -t 2000 "Counting disk space..."
        disk=$( du -xahd1 /home/skontar | sort -h -r | sed 's|/home/skontar/||g' | head -n 11 | tail -n 10 )
        printf "%s" "$disk" | yad --text-info --width 230 --height 170 --no-buttons --title "Disk popup" &
    fi
fi

data=$( df -hl --output=avail,target )
free_root=$( sed -r -n 's|^[[:space:]]+(.*) /$|\1|p' <<< "$data" )
free_home=$( sed -r -n 's|^[[:space:]]+(.*) /home$|\1|p' <<< "$data" )

echo " $free_root  $free_home"
